### ISSUE TITLE
如果有反向代理地址，这要设置在哪？

### ISSUE THREAD

**Issue by 1371030** [panyanyany/muchat-aio#3]
如果有反向代理地址，这要设置在哪？

**Comment by panyanyany** [comment]
什么意思呢，能举个例子吗

**Comment by JeazW** [comment]
意思就是，由于api.openai.com这个接口国内服务器无法访问，就使用一些手段代理成自己的域名api.mydomain.com

**Comment by dizhichao777** [comment]
同问，就是请求地址怎么改？想改成：https://openai.api2d.net

**Comment by panyanyany** [comment]
更新了，可以修改，参考教程：  
https://github.com/panyanyany/muchat-aio#%E4%BD%BF%E7%94%A8%E5%9B%BD%E5%86%85%E4%B8%AD%E8%BD%ACapi
